---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "apl.fullname" . }}
  labels: {{- include "apl.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels: {{- include "apl.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: busybox
          image: busybox
          command: [sleep, '{{ .Values.wait }}']
