---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "apl-test.fullname" . }}
  labels: {{- include "apl-test.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels: {{- include "apl-test.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: busybox
          image: busybox
          command: [sleep, '10']
